### ISSUE TITLE
respimg talk: candidate from src is missing in srcset

### ISSUE THREAD

**Issue by aFarkas** [brucelawson/brucelawson.github.io#1]
In your latest talk about respimg you leave out the [image candidate from the `src` attribute](https://github.com/brucelawson/brucelawson.github.io/blob/master/talks/2015/respimg/index.html#L276-L299).

Example:

``` html
<img src="medium.png"
    alt="mankini"
    srcset="big.png 960w, 
    small.png 240w">
```

This means, that a browser supporting `srcset` with the _w_ descriptor can never choose the medium.jpg.

I assume you want to do this:

``` html
<img src="medium.png"
    alt="mankini"
    srcset="big.png 960w, 
        medium.png 480w,
    small.png 240w">
```

Otherwise I would re-name _medium.jpg_ into _fallback.jpg_ to make clear in your slides, that you explicitly don't want to see _medium.jpg_ eh _fallback.jpg_ displayed by a modern browser.

**Comment by brucelawson** [comment]
"re-name medium.jpg into fallback.jpg to make clear in your slides" < good plan; thanks. Done.
